# -*- mode: ruby -*-
# vi: set ft=ruby :

###############
#  Variables  #
###############

CPUS = 2
RAM = 2048

#######################
#  Provision Scripts  #
#######################

$bootstrap_ubuntu= <<-SCRIPT
# Install dependencies
sudo apt update
sudo apt install -y git pkg-config gdb bash-completion htop dfc \
                    build-essential autoconf libncurses5-dev \
                    libssl-dev bison flex libelf-dev linux-headers-$(uname -r)
SCRIPT

Vagrant.configure("2") do |config|

  config.vm.define "kerneldev" do |kerneldev|
    kerneldev.vm.box = "bento/ubuntu-18.04"
    kerneldev.vm.hostname = "kerneldev"
    kerneldev.vm.provision :shell, inline: $bootstrap_ubuntu

    # VirtualBox-specific configuration
    kerneldev.vm.provider "virtualbox" do |vb|
      vb.name = "kerneldev"
      vb.memory = RAM
      vb.cpus = CPUS
      vb.customize ["setextradata", :id, "VBoxInternal/CPUM/SSE4.1", "1"]
      vb.customize ["setextradata", :id, "VBoxInternal/CPUM/SSE4.2", "1"]
    end
  end

end
