#
# makefile
# zuo, 2019-12-03 20:38
#

.PHONY: luaint.out luastack.out

all: luaint.out luastack.out

luaint.out:
	gcc -o ./luaint.out ./luaint.c -llua5.2

luastack.out:
	gcc -o ./luastack.out ./luastack.c -llua5.2


# vim:ft=make
#
