---
- hosts: all
  become: yes

  vars:

  tasks:
    - name: "Update apt repo"
      become: true
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600

    - name: "Install Bochs emulator and related tools for OS dev and emulation"
      become: true
      apt:
        name:
          - bochs
          - nasm

        state: latest
