# -*- mode: ruby -*-
# vi: set ft=ruby :

###############
#  Variables  #
###############

CPUS = 2
RAM = 1024

#######################
#  Provision Scripts  #
#######################

$bootstrap_ubuntu= <<-SCRIPT
# Install dependencies
sudo apt update
sudo apt install -y git pkg-config gdb bash-completion htop dfc \
                    build-essential autoconf libncurses5-dev \
                    libssl-dev bison flex libelf-dev
SCRIPT

Vagrant.configure("2") do |config|

  config.vm.define "just4fun" do |just4fun|
    just4fun.vm.box = "bento/ubuntu-18.04"
    just4fun.vm.hostname = "just4fun"
    just4fun.vm.provision :shell, inline: $bootstrap_ubuntu

    # VirtualBox-specific configuration
    just4fun.vm.provider "virtualbox" do |vb|
      vb.name = "just4fun"
      vb.memory = RAM
      vb.cpus = CPUS
      vb.customize ["setextradata", :id, "VBoxInternal/CPUM/SSE4.1", "1"]
      vb.customize ["setextradata", :id, "VBoxInternal/CPUM/SSE4.2", "1"]
    end
  end

end
